version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/src/e2e"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/website/ontos"
    schedule:
      interval: "weekly"
