"""
Unit tests for the PDF resolution branch (Volume vs local fs).

Regression target: `download_agreement_pdf` originally used `os.path.isfile()` +
raw `open()` on the persisted `pdf_storage_path`. Inside the Databricks Apps
runtime, `/Volumes/...` is not a real filesystem mount — `isfile()` returned
False and the endpoint silently fell through to fpdf2 regeneration, producing
a PDF with a different `/CreationDate` than the one persisted.

The fix routes `/Volumes/` paths through `WorkspaceClient.files.download()`
while keeping the plain `open()` path for local-dev (non-`/Volumes/`) paths.

Per PR #315 review: the resolution + generation logic moved out of the route
handler and into ``AgreementWizardManager.get_agreement_pdf``. These tests
target the manager method directly (where the branching lives).
"""
from __future__ import annotations

from io import BytesIO
from types import SimpleNamespace
from unittest.mock import MagicMock, patch

from src.controller.agreement_wizard_manager import AgreementWizardManager


def _make_agreement(*, pdf_storage_path: str | None, with_pdf_step: bool = True):
    """Minimal stand-in for the AgreementDb row."""
    snapshot = (
        '{"steps": [{"step_id": "pdf", "step_type": "generate_pdf", "config": {}, "order": 0}]}'
        if with_pdf_step
        else '{"steps": []}'
    )
    return SimpleNamespace(
        id="agr-12345678",
        workflow_id="wf-1",
        workflow_name="Approval WF",
        workflow_snapshot=snapshot,
        workflow_version=1,
        entity_type="data_product",
        entity_id="entity-1",
        step_results="[]",
        pdf_storage_path=pdf_storage_path,
        created_by="signer@example.com",
        created_at=None,
    )


class TestPdfDownloadVolumeBranch:
    """Verify get_agreement_pdf routes /Volumes/ paths through the SDK."""

    def test_volume_path_uses_files_api(self):
        """When pdf_storage_path is /Volumes/..., SDK download is used."""
        fake_pdf = b"%PDF-1.4 stored-bytes"
        volume_path = "/Volumes/cat/sch/vol/agreements/agr-12345678.pdf"
        agreement = _make_agreement(pdf_storage_path=volume_path)

        mock_resp = MagicMock()
        mock_resp.contents = BytesIO(fake_pdf)
        mock_ws = MagicMock()
        mock_ws.files.download = MagicMock(return_value=mock_resp)

        manager = AgreementWizardManager(db=MagicMock())

        with patch(
            "src.controller.agreement_wizard_manager.agreements_repo.get",
            return_value=agreement,
        ), patch(
            "src.common.workspace_client.get_workspace_client",
            return_value=mock_ws,
        ):
            result = manager.get_agreement_pdf("agr-12345678")

        # SDK was called with the stored Volume path
        mock_ws.files.download.assert_called_once_with(file_path=volume_path)
        # And the result contains the SDK-fetched bytes (not regenerated ones)
        assert result["kind"] == "pdf"
        assert result["content"] == fake_pdf

    def test_volume_download_failure_falls_through_to_regeneration(self):
        """If the SDK download raises, regeneration is the final fallback."""
        volume_path = "/Volumes/cat/sch/vol/agreements/agr-12345678.pdf"
        agreement = _make_agreement(pdf_storage_path=volume_path)

        mock_ws = MagicMock()
        mock_ws.files.download = MagicMock(side_effect=Exception("Permission denied"))

        regenerated_pdf = b"%PDF-1.4 regenerated"

        manager = AgreementWizardManager(db=MagicMock())

        with patch(
            "src.controller.agreement_wizard_manager.agreements_repo.get",
            return_value=agreement,
        ), patch(
            "src.common.workspace_client.get_workspace_client",
            return_value=mock_ws,
        ), patch(
            "src.utils.agreement_pdf_builder._HAS_FPDF", True
        ), patch(
            "src.utils.agreement_pdf_builder.build_agreement_pdf",
            return_value=bytearray(regenerated_pdf),
        ):
            result = manager.get_agreement_pdf("agr-12345678")

        # SDK was attempted
        mock_ws.files.download.assert_called_once()
        # Result is the regenerated bytes — manager did not raise
        assert result["kind"] == "pdf"
        assert result["content"] == regenerated_pdf

    def test_local_path_uses_open_fallback(self, tmp_path):
        """For non-/Volumes/ paths, raw open() is still used (dev compat)."""
        fake_pdf = b"%PDF-1.4 local-bytes"
        local_pdf = tmp_path / "agr-12345678.pdf"
        local_pdf.write_bytes(fake_pdf)

        agreement = _make_agreement(pdf_storage_path=str(local_pdf))

        mock_ws = MagicMock()  # must NOT be invoked
        manager = AgreementWizardManager(db=MagicMock())

        with patch(
            "src.controller.agreement_wizard_manager.agreements_repo.get",
            return_value=agreement,
        ), patch(
            "src.common.workspace_client.get_workspace_client",
            return_value=mock_ws,
        ):
            result = manager.get_agreement_pdf("agr-12345678")

        assert not mock_ws.files.download.called, (
            "SDK Files API must not be called for non-/Volumes/ paths"
        )
        assert result["kind"] == "pdf"
        assert result["content"] == fake_pdf
