"""
Unit tests for the co-signer rendering helper in agreement_pdf_builder.

Regression target: both build_agreement_pdf (line ~115) and
build_agreement_html (line ~258) previously rendered each co-signer entry via
f-string interpolation / str() on the dict, producing literal
``{'type': 'user', 'value': ...}`` text in the persisted artifact (caught
during inspection of the subscribe-on-behalf demo PDFs in the Volume).

These tests exercise the new ``_format_cosigner`` helper directly plus a
PDF/HTML smoke test confirming the readable text actually lands in the
generated bytes / markup.
"""
from __future__ import annotations

import json
from unittest.mock import patch

import pytest

from src.utils.agreement_pdf_builder import (
    _HAS_FPDF,
    _format_cosigner,
    build_agreement_html,
    build_agreement_pdf,
)


# ---------------------------------------------------------------------------
# Helper unit tests
# ---------------------------------------------------------------------------
class TestFormatCosigner:
    """Direct coverage of the rendering rules."""

    def test_format_cosigner_dict_with_display_and_value(self):
        s = {"type": "user", "value": "alice@x.com", "display": "Alice"}
        assert _format_cosigner(s) == "Alice (alice@x.com)"

    def test_format_cosigner_dict_value_only(self):
        # No display key -> fall back to value.
        s = {"type": "user", "value": "alice@x.com"}
        assert _format_cosigner(s) == "alice@x.com"

    def test_format_cosigner_dict_display_equals_value(self):
        # Don't double-render when display and value are the same.
        s = {"display": "alice@x.com", "value": "alice@x.com"}
        assert _format_cosigner(s) == "alice@x.com"

    def test_format_cosigner_legacy_string(self):
        # Older sessions stored plain strings — backwards compat.
        assert _format_cosigner("Alice") == "Alice"

    def test_format_cosigner_unknown(self):
        # Neither display nor value present.
        assert _format_cosigner({"type": "user"}) == "(unknown)"


# ---------------------------------------------------------------------------
# Smoke tests on the actual PDF/HTML builders to make sure the helper is
# wired in at both render sites.
# ---------------------------------------------------------------------------
def _snapshot_with_cosigner_step() -> str:
    return json.dumps({
        "steps": [
            {
                "step_id": "cs",
                "step_type": "co_signers",
                "name": "Co-Signers",
                "config": {},
                "order": 0,
            }
        ]
    })


@pytest.mark.skipif(not _HAS_FPDF, reason="fpdf2 not installed")
def test_build_agreement_pdf_does_not_leak_dict_repr_for_cosigners():
    """
    Regression guard: with the buggy ``f"  - {s}"`` interpolation the dict
    repr (``{'type': 'user', ...}``) ends up rendered into the PDF body.
    fpdf2 flate-compresses content streams, so we can't easily assert the
    formatted display string lands in the bytes; instead we patch the
    `pdf.cell` write path to capture every line that gets written and
    assert against the captured strings directly. This still verifies the
    helper is wired into ``build_agreement_pdf`` without depending on a
    PDF text extractor at test time.
    """
    snap = _snapshot_with_cosigner_step()
    step_results = [
        {
            "step_id": "cs",
            "payload": {
                "co_signers": [
                    {"type": "user", "value": "thomas.mueller@.example",
                     "display": "Thomas Mueller"}
                ]
            },
        }
    ]
    captured: list[str] = []

    # Wrap FPDF.cell so we can see every text fragment written.
    from fpdf import FPDF
    real_cell = FPDF.cell

    def spy_cell(self, w, h=0, txt="", *args, **kwargs):
        # fpdf2 calls cell with positional or keyword text; capture both.
        text = txt
        if not text and args:
            # Older signatures put text differently; try the first str arg.
            for a in args:
                if isinstance(a, str):
                    text = a
                    break
        captured.append(str(text))
        return real_cell(self, w, h, txt, *args, **kwargs)

    with patch.object(FPDF, "cell", spy_cell):
        out = build_agreement_pdf(
            workflow_name="Demo",
            entity_type="data_product",
            entity_id="entity-1",
            step_results=step_results,
            snapshot=snap,
            created_by="signer@example.com",
        )

    # PDF was actually produced.
    assert bytes(out).startswith(b"%PDF")

    # No dict-repr leaked into any rendered cell.
    joined = "\n".join(captured)
    assert "{'type'" not in joined, (
        f"co-signer dict-repr leaked into a PDF cell: {joined!r}"
    )
    # Formatted readable text is what reaches the PDF.
    assert "Thomas Mueller (thomas.mueller@.example)" in joined


def test_build_agreement_html_renders_cosigner_display_text():
    snap = _snapshot_with_cosigner_step()
    step_results = [
        {
            "step_id": "cs",
            "payload": {
                "co_signers": [
                    {"type": "user", "value": "alice@x.com", "display": "Alice"}
                ]
            },
        }
    ]
    out = build_agreement_html(
        workflow_name="WF",
        entity_type="data_product",
        entity_id="entity-1",
        step_results=step_results,
        snapshot=snap,
        created_by="signer@example.com",
    )
    # No dict-repr leaking in HTML either.
    assert "{&#x27;type&#x27;" not in out and "{'type'" not in out
    assert "Alice (alice@x.com)" in out


def test_build_agreement_html_renders_legacy_string_cosigner():
    snap = _snapshot_with_cosigner_step()
    step_results = [
        {"step_id": "cs", "payload": {"co_signers": ["Alice"]}}
    ]
    out = build_agreement_html(
        workflow_name="WF",
        entity_type="data_product",
        entity_id="entity-1",
        step_results=step_results,
        snapshot=snap,
        created_by="signer@example.com",
    )
    # Backwards-compat: plain strings still render.
    assert "Alice" in out
